version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: docusaurus
    versions:
    - 1.14.6
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
