version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}
        
      - run: 
          name: Build project
          path: website
          command: yarn build
