version: 2
jobs:
  build:
    docker:
      - image: circleci/node:alpine
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn build
