version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          path: website
          command: yarn

      - save_cache:
          name: Save cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}
      
      - run:
          name: Prettier
          path: website
          command: yarn lint:prettier

      - run:
          name: Eslint
          path: website
          command: yarn lint:eslint

      - run: 
          name: Build project
          path: website
          command: yarn build

  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t itdagene/docs:$CIRCLE_BRANCH .
      - run: docker push itdagene/docs:$CIRCLE_BRANCH

workflows:
  version: 2
  on_push:
    jobs:
      - tests
      - build:
          requires:
            - tests
          filters:
            branches:
              only:
                - prod
